### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by andig** [andig/evcc-image#1]
- [ ] move ports 80 and 443 out of the way to be usable by evcc
- [ ] learn how to had persistent files on build time
- [ ] add evcc public certificate
- [ ] add an evcc default config
- [ ] integrate building the image with evcc release process

**Comment by fawick** [comment]
One idea to address the config: 
- Embed a minimum viable config file in the executable to let the application start without the external config file.  
- Create GUI for changing all  settings in the frontend. 
- Then write the config file directly from EVCC to `/perm`.

**Comment by fawick** [comment]
Another idea for storing the SSHD keys as well the authorized keys: 
- Use Travis CI or similar product to create an image automatically. Do not write the image to an SD device, but to a file and run `mkfs.ext4`, `ssh-keygen` with travis.
- Create UI in the frontend to upload public SSH keys.

However, ideally breakglass/SSH will no longer be needed for end-users once all configuration settings can be set from the UI.

**Comment by andig** [comment]
> Embed a minimum viable config file in the executable to let the application start without the external config file.

Yep, das ist der vorletzte Punkt oben.

**Comment by andig** [comment]
> Use Travis CI or similar product to create an image automatically. Do not write the image to an SD device, but to a file and run mkfs.ext4, ssh-keygen with travis.

Any idea how to do that on github actions? At time of build, the image is still only written to file?
